//The model is where we store all the data so the controller can manipulate it later.
const model = {
  //The view field gets the container in the HTML by ID, making it easier to update
  view: document.getElementById("app"),

  //the click icon is the image you click to gain ears
  clickIcon: {
    img: "../Media/Dohya big.png",
  },

  //the buy icon is theone you click to buy another emote
  buyIcon: {
    img: "../Media/Mogu big.png",
  },
  
  // icon representing points
  mimiIcon: {
    img: "../Media/mimi.png",
  },

  currentPoints: 0,

  //points per click is how many ears you get for clicking the click icon
  pointsPerClick: 1,

  //points over time increases how many ears you get even when not clicking
  pointsOverTime: 0,

  //The emote list loads the pictures so they can be used in the code
  //img is the file path. 
  //ppc is points per click modifier
  //pot is points over time modifier
  //price is the cost of buying a new icon
  //amount is how many emotes are purchased of this kind
  //iscat is for determining if ppc or pot will increase
  //default value is 0, but it is modified later
  emoteList: [
    {
      img: "../HaruEmotes/Attack.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/AYAYA.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Bara.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/catJAM.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: false,
    },
    {
      img: "../HaruEmotes/CatRoll.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: false,
    },
    {
      img: "../HaruEmotes/Clap.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Comfy.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Dance.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Doya.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Drive.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Gaan.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Ganbae.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/GG.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/GL.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Good.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Guruguru.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Hatena.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Hi.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/HYPE.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/JAM.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/JAMJAM.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Kokeru.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Korokoro.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Kusa.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Love.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Maru.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Memo.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Neteru.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/NYA.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Nyaruhodo.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/party.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Pat.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/PogS.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Pray.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Rainbow.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Roll.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Shigeru.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: false,
    },
    {
      img: "../HaruEmotes/Shock.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Spin.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Waa2.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/WAA.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/WAWA.gif",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Why.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
    {
      img: "../HaruEmotes/Yoshi.png",
      ppc: 0,
      pot: 0,
      price: 0,
      amount: 0,
      isCat: true,
    },
  ],
};
